palette = "tokyonight-night"

[palettes.tokyonight-night]
bg = "#1a1b26"
fg = "#c0caf5"
terminal_black = "#414868"
terminal_dark = "#303030"
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
