palette = "tokyonight-storm"

[palettes.tokyonight-storm]
bg = "#24283b"
fg = "#c0caf5"
terminal_black = "#414868"
terminal_dark = "#303030"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
red = "#f7768e"
yellow = "#e0af68"
white = "#a9b1d6"
