{
	"data": "ENC[AES256_GCM,data:tMbRXMaoJf40zWa0YrgkQLuQEqgzxImIzDRAO7H95mXaqf54YptdbeP0RFqfjdK7yIvJf47F2xkRbctGtao//F4AIVbzQMKFSVQ1GerFS9Io/WVHPVeY3V1LonFLBYD5md5b79G2Jl14Z0mF0WadbNdvF3QcSeeQAu3/5X+N/JxlcgrVNRcci18XeB5Ql3PB4PPGx9U=,iv:z3y8YqPw6lqN9/BDGN+I9oDCDsnIzUTN+LLo4zyjem8=,tag:zwNoVt0c2NzYqe+OGx4McQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1w4dld6acqnhctzq32nhnajw0ewgkq7295k3ue3cgg0pwpt0re3asg4ajs3",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYlVxZllKY3FEVW5JN2tQ\nMkthcDVUWEx3aFVwb0VJc05GbkJwOUsrVmpVCkZpVDRKakorWjVhL1hvMHN2RzlT\nNUJPTFg2U2psUTNpU1A1a3FSQXFwb0EKLS0tIG5WcXFCdkpkazhiU05JTjQ0bDZv\nWnpHbXAvYXZNVFZ1K3dHM09tNHNSZncK8FRSPG3rZg/xqDaVts+5kfxUa7IN8CYU\nDpymj8iNtshbREzayQdPppUX/S4mr2IXY4ykbhYblRC5Afg1ZdZssg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1znnqnxjkr0x70r5ys0n2k34ym5a3spn69yuveqa76wh0ng65catspphysl",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TjhYV1dYZHoyMnFkZTdY\nZ1RwbjRmUkdubXVUaDVJU3Y3a2FEZlZXWUgwCnRsSDVIcG1HRStVVlNCc1NpNys0\nVjZkUkJhbWRtckdwQWVzb201MUIvOHcKLS0tIFdwQkpZYW4zaExRNjFiMzN2dzVM\nN2ttWnBJVDBsMEV1c0dKYUFEaDdwTzgKcvAFpBFTNyPLsaM1E8RO+RS/365EI7a1\nogJbohSOJ2HHm3BiYzlX1QYgR3J0jyVwYjDuqopYFPV7j7eLLkYqgg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1qggvd6rfs83grgl5u05cythrtc8ny2dkq9ad53lsfekmg2fk7dfqgnt6p5",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcUM0VEFSQmlWL2wyeWFn\nalN1d3hvbUF6Vzk1ZlUvVXBYRk5ydmNseUJzCjJRa010TyszWncxdGVPdmpDM2p2\nWGdBWUJiVGVvalJReVhJaEU4ODEzZGcKLS0tIGt4eTVtOUlZakdUQWpHYWx1TVpm\nbE9hVUh3Y253SlN0MWxqQjlzNElqS1EKLmnKDKHSvSvql2cqptNlWqCu2S0waNC2\nElPMVtctDf5bwy71OxSJlEFbBck/zCAe+KrP5CiHYgLfjQ++8nSg3A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-07-03T00:41:22Z",
		"mac": "ENC[AES256_GCM,data:SwTPr/WH9AVdZZHrt4kGHngdG0uDpGSxC0xxHS/oTQbC3bhZsnwqfSk+IuR6brZUVEb1EYeUgEJWN3WUvYbLeG0dnXRW+/4w1NHS3aYP3h9fmuBU6mS8qvGXDhjfINLByCaXIUaxMTd9divPsxEv5l6jiNzmJ7Du+6npwmrGTpU=,iv:M0lUzVjymaJoR9VsBzfcWFhym1N3WWaJUyBJlIuP5f0=,tag:zhv4ikObnbq33MWeSR6czQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}