{
	"data": "ENC[AES256_GCM,data:hTK1Obm3PQ0HvVihLC441/OXspM1vChrNJC0EsI/I9RrhjgjNfJqIqSks4ztte1NT7ldZnVgdTB1jouwCml6c0MySAWYBIz6Pl9HwaYZ2Ve2RM0TGGdKh8dczNig,iv:YJzib18lr5cIdGB0VFZA0MUNMQXTR8LEwgqjqP9qWe4=,tag:lwEGHAxsG6ZYKhjPrsyJbg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1w4dld6acqnhctzq32nhnajw0ewgkq7295k3ue3cgg0pwpt0re3asg4ajs3",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUm00YXVnTmRtaUVjOVRQ\nTG1LaFZWWDFIM2pEd2dVeXdoa2pNbzJCaEJRCmtHVm5HeGZ6aVNTSS9MeUJYaEk2\nbkJXaFJNK1FvZ01mbUMycFdhUGFreUUKLS0tIG9YSXJWUFZMejA0RjBKbW10bkNq\nKzE4akZYaEwzbkpuUDJGWVNFQnk4TzAKPT/7kmWxLBQ0aXi/PDUeqZFL+uJYjJ3K\nrzgb/jrggwIJPN7Uaz9YQdWjL9Bn/qJ57UfWNT2N5xP1F+BFlhBt6g==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1znnqnxjkr0x70r5ys0n2k34ym5a3spn69yuveqa76wh0ng65catspphysl",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTEM1TGJvTitGRVNIUFVB\nNzN3SjVlSUJXM1F1SXYrK3AvR1Y5a1liSkIwClZwekdkcDk5TUpCb3dlTW5FZnpZ\nazU2bTZMaDRKYlVHL2xwaVdJTzJwKzQKLS0tIElwYXgvZXBIa214VHNBTjNJblZy\nMEJuQ0w5RVFwVGdYcVl3dkFOandlakkKCPsEKOyKNHe5jtWdhNpsGfpgzfNJYDrz\nPNj21rd6kIDbV3ZKtMZjGtavbYY77qGqocVQ9gavorH5WCZP07tA/w==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1qggvd6rfs83grgl5u05cythrtc8ny2dkq9ad53lsfekmg2fk7dfqgnt6p5",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHd1JKTFBLWHBhcXExdGJI\nc3I4M2w0blFmT1BOYjlDNU5JcDFMd0QzNkZRCk9YUXFrdVdpZFVsRGVaZlU1a2xh\nT2ZQN3BDdXRKK3p3RzhiWkM5bTI2UzAKLS0tIDdxVUZxMFRKMjdlOVJjSzBHWEdO\nUFByV25hOGI3KzdlLzJzNWx3ZG1KOVkKWZLYdHqN9PFZdYcPJmMHlBLDMIomdxAF\nfD8psrM+kDPJaHTDKVWJtmP9KLJWKy5QQmGLAXBghpanTsqrLJ79Qg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-07-03T07:43:48Z",
		"mac": "ENC[AES256_GCM,data:QZjVQ/JUWRp5FEJxExV5OrjWb2Q8VFGJY3LYQS2jv2ZyG+UISWcr+3NCOvz+Yd7eOR8tAiu4sw41XZxVsIvKLzpbimenk+7jrAwiMwTMUT41UX2aNUD3qnUVLdtoygcfhKbAIllwh+dL5AhErLEzD/xatQC67oJCuM2wLDGuuFw=,iv:rGCBPvxs9BEg6zEhCN0JeV5Qby4J3pVwZmHFBtQgQKQ=,tag:kpdy9zNNSBkmNi+2TfN1bQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}