name: Build check
on:
  pull_request:

jobs:
  build-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'misumisumi'
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          build-mount-path: "/nix/store"
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run flake build
        run: nix build --no-link ".#nixosConfigurations.test.config.system.build.toplevel"

      - name: Save PR number
        run: echo $GITHUB_REF | sed -e 's/[^0-9]//g' > pr-number.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-number
          path: pr-number.txt
          retention-days: 7

  bypass-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'misumisumi'
    steps:
      - name: Save PR number
        run: echo $GITHUB_REF | sed -e 's/[^0-9]//g' > pr-number.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-number
          path: pr-number.txt
          retention-days: 7
