name: build check
on:
  pull_request:

permissions:
  id-token: "write"
  contents: "read"

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: change
        with:
          filters: |
            nix:
              - "**.nix"
              - "flake.lock"

      - uses: easimon/maximize-build-space@master
        if: steps.change.outputs.nix == 'true'
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          build-mount-path: "/nix/store"
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - uses: actions/checkout@v4
        if: steps.change.outputs.nix == 'true'

      - uses: cachix/install-nix-action@V27
        if: steps.change.outputs.nix == 'true'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            connect-timeout = 15
            stalled-download-timeout = 15

      - name: Build check
        if: steps.change.outputs.nix == 'true'
        run: nix build --no-link ".#nixosConfigurations.liveimg-gui-full.config.system.build.toplevel"
